name: projectverbosity
dependencies:
- openssl=1.0.2h=0
- pip=8.1.1=py34_1
- python=3.4.4=0
- readline=6.2=2
- setuptools=21.2.1=py34_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py34_0
- xz=5.0.5=1
- zlib=1.2.8=3
- pip:
  - argh==0.26.2
  - cython==0.24
  - docutils==0.12
  - gitdb==0.6.4
  - gitpython==2.0.5
  - jedi==0.9.0
  - kivy==1.9.1
  - kivy-garden==0.1.4
  - pathtools==0.1.2
  - pillow==3.2.0
  - pygame==1.9.2.dev1
  - pygments==2.1.3
  - pyyaml==3.11
  - requests==2.10.0
  - six==1.10.0
  - smmap==0.9.0
  - watchdog==0.8.3

